### ISSUE TITLE
Developing the SoftNeckControl device

### ISSUE THREAD

**Issue by PeterBowman** [HUMASoft/yarp-devices#1]
I'm going to post here all relevant info regarding the WIP [*SoftNeckControl* device](https://github.com/HUMASoft/yarp-devices/tree/master/libraries/YarpPlugins/SoftNeckControl) ([permalink](https://github.com/HUMASoft/yarp-devices/tree/15eb4590873fc3317b96794af4cb478aefd5118c/libraries/YarpPlugins/SoftNeckControl), barely just the skeleton of a new library).

This device aims to implement the [`roboticslab::ICartesianControl` interface](https://github.com/roboticslab-uc3m/kinematics-dynamics/blob/5877cc15f35220012d00a3ee61dee43773c4095c/libraries/YarpPlugins/ICartesianControl.h) ([doxy](http://robots.uc3m.es/dox-kinematics-dynamics/classroboticslab_1_1ICartesianControl.html)) and thus resemble the [*BasicCartesianControl* device](https://github.com/roboticslab-uc3m/kinematics-dynamics/tree/5877cc15f35220012d00a3ee61dee43773c4095c/libraries/YarpPlugins/BasicCartesianControl) (a generic open-chain cartesian controller).

The implementation itself, i.e. the control scheme we must somehow code into said interface, is best described [in the *imufb-inc-fo-yes* demo](https://github.com/HUMASoft/demos/blob/0cc0ca65a5f2ece627fd3483cd7d177a148e802c/main/imufb-inc-fo-yes.cpp).

**Comment by PeterBowman** [comment]
First step: implement open-loop commands, see [*ol-pos-360* demo](https://github.com/HUMASoft/demos/blob/0cc0ca65a5f2ece627fd3483cd7d177a148e802c/main/ol-pos-360.cpp).

**Comment by PeterBowman** [comment]
The serial device is correctly started with:

```
yarpdev --device serialport --comport /dev/ttyACM0 --baudrate 9600 --paritymode NONE --databits 8 --stopbits 1
```

However, the outgoing messages are split in weird places, i.e. we read whatever is stored in the buffer. These messages need to be parsed with an accumulator and split on line endings (`\n` chars).

That is, we see:

```
"i0.55,o288.1"
"7\ni0.79,o282"
".96\ni0.9"
```

We would like to see:

```
"i0.55,o288.17\n"
"i0.79,o282.96\n"
```

**Comment by PeterBowman** [comment]
softNeck.ini:

```ini
[devCan0]
device CanBusControlboard
canDevice /dev/pcan1
canBusType CanBusPeak
canBitrate 1000000
types TechnosoftIpos TechnosoftIpos TechnosoftIpos
ids   31 32 33
maxs  90.0 90.0 90.0
mins -90.0 -90.0 -90.0
trs   1.0 1.0 1.0
refAccelerations  0.575437 0.575437 0.575437
refSpeeds  5.0 5.0 5.0
encoderPulsess  2048 2048 2048

[wrapper0]
device controlboardwrapper2
name /softneck
period 60
joints 3
networks (devCan0)
devCan0 0 2 0 2
```

**Comment by PeterBowman** [comment]
I'm willing to treat neck joints as prismatic (instead of revolute). That is, usual motion commands will accept values expressed in meters instead of degrees. The winch radius is 0.0075 meters ([ref](https://github.com/HUMASoft/demos/blob/0cc0ca65a5f2ece627fd3483cd7d177a148e802c/main/imufb-inc-fo-yes.cpp#L88)), hence the transmission ratio (`tr` option) is obtained with the formula `theta = (180 * l) / (pi * r) = tr * l`, where `l` and `theta` denote the output of the IK algorithm and the actual rotation angle of the motors (in degrees), respectively. Therefore, `tr = 7639.437`.

**Comment by rsantos88** [comment]
> softNeck.ini:
> 
> ```ini
> [devCan0]
> device CanBusControlboard
> canDevice /dev/pcan1
> canBusType CanBusPeak
> canBitrate 1000000
> types TechnosoftIpos TechnosoftIpos TechnosoftIpos
> ids   31 32 33
> maxs  90.0 90.0 90.0
> mins -90.0 -90.0 -90.0
> trs   1.0 1.0 1.0
> refAccelerations  0.575437 0.575437 0.575437
> refSpeeds  5.0 5.0 5.0
> encoderPulsess  2048 2048 2048
> 
> [wrapper0]
> device controlboardwrapper2
> name /softneck
> period 60
> joints 3
> networks (devCan0)
> devCan0 0 2 0 2
> ```

I modified this .ini to test exclusively with one motor (for more security)
I have also changed the value from tr to '24' (24:1). @lismena has provided me the motor data. Now I will document this data below. The result is that I managed to move it slightly at a very slow speed. We should to put the correct data of 'refAccelerations' and 'refSpeeds' to get the correct result

**Comment by rsantos88** [comment]
last test (works fine but slow):

```ini
[devCan0]
device CanBusControlboard
canDevice /dev/pcan1
canBusType CanBusPeak
canBitrate 1000000
types TechnosoftIpos
ids   31
maxs  360.0
mins -360.0
trs   24.0
refAccelerations  10.0
refSpeeds  10.0
encoderPulsess  2048

[wrapper0]
device controlboardwrapper2
name /softneck
period 60
joints 1
networks (devCan0)
devCan0 0 0 0 0
```
Checked the correct relation between the out angle of the gearbox and the angle obtained by the encoder :+1:

**Comment by rsantos88** [comment]
Specifications for motors, gearboxes and encoders:

![image](https://user-images.githubusercontent.com/15872457/70141141-a9ecdf00-1696-11ea-824f-f4b4ebe71d03.png)


![image](https://user-images.githubusercontent.com/15872457/70141088-8b86e380-1696-11ea-831d-64144e2ba175.png)

**Comment by rsantos88** [comment]
Updated `softNeck.ini` in reference to https://github.com/HUMASoft/yarp-devices/issues/1#issuecomment-561380749 :

```ini
[devCan0]
device CanBusControlboard
canDevice /dev/pcan1
canBusType CanBusPeak
canBitrate 1000000
types TechnosoftIpos TechnosoftIpos TechnosoftIpos
ids   31 32 33
maxs  90.0 90.0 90.0
mins -90.0 -90.0 -90.0
trs   183346.494 183346.494 183346.494
refAccelerations  0.01 0.01 0.01
refSpeeds  0.01 0.01 0.01
encoderPulsess  2048 2048 2048

[wrapper0]
device controlboardwrapper2
name /softneck
period 60
joints 3
networks (devCan0)
devCan0 0 2 0 2
```

**Comment by PeterBowman** [comment]
Open- and closed-loop `movj` implementations ready (closed-loop still to be tested, although we know the accumulator for serial stream data works nicely), now we need to conform to the `roboticslab::ICartesianControl` interface so that orientations of input/output follow the axis-angle convention. See [this](https://math.stackexchange.com/q/1019910) for a conversion between axis-angle and spherical rotation coordinates (also: [Wikipedia](https://en.wikipedia.org/wiki/Spherical_coordinate_system)).

Alongside the last point, the IK should be rewritten in terms of axis-angle inputs. Also, we would benefit from a FK function, now missing.

**Comment by PeterBowman** [comment]
Okay, now we conform to the interface and implementations for methods `inv`, `movj`, `wait`, `stopControl` and `movi` are ready, also including configuration commands. The `movj` command sends position commands either in open loop (when no serial port is attached to read from the IMU sensor) or closed loop configurations (with IMU feedback).

The actual simplified orientation system in use here is the RPY without roll (about axis X), and closed loop control is performed for pitch angle, only. This means that `movj` in closed loop is faulty whenever commanding distinct yaw values while the pitch is not changing (or barely varies), due to the lack of FK. Next, I suggest to obtain algebraic formulae for the FK of this system and use them in the `stat` command, currently publishing IMU read just for debug purposes. Also, I'd fancy a `computeIk` implementation that accepts axis-angle orientations instead of RPY in order to avoid an otherwise unnecessary conversion step.

The generic *streamingDeviceController* app (from [roboticslab-uc3m](https://github.com/roboticslab-uc3m/kinematics-dynamics) repo) has been tested on this controller in order to perform position control with high-frequency streaming commands (namely, `movi`). Components:

* this repository at [1a2519a](https://github.com/HUMASoft/yarp-devices/tree/1a2519ac444b0258c53e72194c4fd267f38c8c6e), see installation guide in README
* [*softNeckControl.xml*](https://github.com/HUMASoft/yarp-devices/blob/1a2519ac444b0258c53e72194c4fd267f38c8c6e/share/applications/yarpmanager/softNeckControl.xml) lists all relevant modules required for this demonstration
* https://github.com/roboticslab-uc3m/yarp-devices/commit/3f93c5940a764e384ba72f70cf4d377009f68cf5
* https://github.com/roboticslab-uc3m/kinematics-dynamics/commit/1d5a85c2fe1bdcda477d3641b99d50405ee21e7b

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/8AsrKjzjGpg/0.jpg)](https://www.youtube.com/watch?v=8AsrKjzjGpg)

**Comment by PeterBowman** [comment]
BTW now I see that the RPY angle representation might not be the best choice, although it seemed to work somehow at a first glance. On a second thought, I'm more inclined into a derivate from an axis-angle representation in which the Z component is always null (thanks @jgvictores). Thus, given the theta polar angle and phi azimuthal angles as inputs that encode an orientation of the oscillating plate ([wiki](https://en.wikipedia.org/wiki/Spherical_coordinate_system)), the `k` axis of rotation is given by `(kx, ky, 0)`, where `tan(phi) = -kx / ky`, and the angle of rotation about said axis equals theta.

**Comment by PeterBowman** [comment]
> BTW now I see that the RPY angle representation might not be the best choice, although it seemed to work somehow at a first glance.

Fixed in https://github.com/HUMASoft/yarp-devices/commit/9391df42dbd8015ae01da40ce79f54f2d67a0185, now we use the axis-angle representation instead (this is **not** the scaled axis-angle representation) and the 3D mouse commands correctly map to the targeted neck orientation:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/k51_2hF2MbA/0.jpg)](https://www.youtube.com/watch?v=k51_2hF2MbA)
