### ISSUE TITLE
Closed-loop control should perform in a continuous fashion [es]

### ISSUE THREAD

**Issue by rsantos88** [HUMASoft/yarp-devices#3]
Ayer haciendo pruebas con el nuevo código, pude constatar que actualmente el bucle cerrado en inclinación y orientación que ejecuta hasta llegar al nuevo target y la posterior reorientación en bucle abierto no está funcionando correctamente. Concretamente, al llegar al target de orientación, hace una parada (hasta aquí correcto) pero luego tiende a recuperar la posición inicial, volviendo a una inclinación y orientación cercana a 0.
Por el momento, y para hacer pruebas con el sensor, he comentado [este código](https://github.com/HUMASoft/yarp-devices/blob/master/libraries/YarpPlugins/SoftNeckControl/PeriodicThreadImpl.cpp#L82-L98), aunque aún no lo he subido a la rama `master` de este repositorio por si se quisiera revisar.

**Comment by PeterBowman** [comment]
Bugs aparte que pueda haber, la solución actual es solo una aproximación que carece de una condición de parada apropiada, la cual consistiría en comandar la inclinación resultante de un cálculo de la FK en dicho instante (https://github.com/HUMASoft/yarp-devices/issues/2) y la orientación original enviada por `movj`. Además, probablemente obstruya este proceso el continuo cálculo de las velocidades de referencia en `sendTargets`.

**Comment by PeterBowman** [comment]
Ayer hablándolo con Raúl convenimos que la condición de parada del target es innecesaria para este caso de uso dado que obvia en gran medida la presencia y el buen o mal funcionamiento del bloque de control. Es decir, ahora mismo estamos forzando una parada cuando los motores se aproximan al objetivo. De no existir dicha condición, el cuello podría oscilar en torno a este target y estabilizarse finalmente, como vemos que ocurre si le dejamos actuar, o inestabilizarse y continuar moviendo hasta algún límite articular. Por ello es interesante permitir que el controlador siga aplicando la acción de control y actualizar sus parámetros internos a medida que van llegando nuevos targets, es decir, estar *siempre* realizando control.

Distinguimos entonces dos modos de funcionamiento de este device, al menos en lo que concierne al comando `movj`:

* Control en lazo abierto, sin IMU, simplemente realizando un cálculo de cinemática inversa al inicio y dejar que construya la trayectoria y la ejecute una vez. Aquí nunca actualizamos los parámetros de la trayectoria salvo que llegue otro target vía `movj`. Así es como funciona en la actualidad.

* Control en lazo cerrado si instanciamos el device con la IMU. El hilo del lazo de control está continuamente actualizando el target en función de la lectura del sensor y la salida del lazo de control. Para implementar esto simplemente quitaremos las condiciones de parada y prepararemos el device para que sepa que siempre está controlando y a la espera de nuevos targets.

**Comment by rsantos88** [comment]
Efectivamente, y como ya se ha habló en la reunión anterior, nos interesa eliminar esa condición de parada, así como el timeout de los 5 segundos, y permitir que el controlador siga aplicando la acción de control de manera continuada haciendo uso de los datos de entrada de la IMU. Añadiendo un apunte a esto, el último día estuve experimentando con el comportamiento del controlador en bucle cerrado de la inclinación, y pude constatar que existe una sobreoscilación bastante notable del controlador. Esto da lugar a que, si por ejemplo comandamos el cuello para que se mueva 10 grados en inclinación, el sistema sobrepasará con bastante diferencia, el target especificado y posteriormente retornará volviendo a alejarse del target en dirección contraria, oscilando así un rato sobre éste hasta estabilizarse y alcanzar la posición requerida. Si a esto le sumo el control en orientación, el sistema se vuelve más inestable aún porque estaríamos oscilando sobre 2 parámetros a la vez; inclinación y orientación. Hablándolo con Bartek, me comentaba la posibilidad de que el controlador se tenga que configurar atendiendo a las condiciones en las que realicemos el experimento, como puede ser el peso que exista sobre el cuello u otra serie de requisitos. ¿es esto así? ¿se podría afinar más el controlador para conseguir reducir esa sobreoscilación?

**Comment by PeterBowman** [comment]
> Control en lazo cerrado si instanciamos el device con la IMU. El hilo del lazo de control está continuamente actualizando el target en función de la lectura del sensor y la salida del lazo de control. Para implementar esto simplemente quitaremos las condiciones de parada y prepararemos el device para que sepa que siempre está controlando y a la espera de nuevos targets.

> Efectivamente, y como ya se ha habló en la reunión anterior, nos interesa eliminar esa condición de parada, así como el timeout de los 5 segundos, y permitir que el controlador siga aplicando la acción de control de manera continuada haciendo uso de los datos de entrada de la IMU.

Hecho en https://github.com/HUMASoft/yarp-devices/commit/5765c6da93b1d436befb9ec907b7ac1e760fe3da. Ya no hay condiciones de parada en lazo cerrado, el hilo secundario estará siempre enviando targets y actualizándose según lleguen nuevas posiciones mediante `movj` hasta que alguien ejecute el comando `ICartesianControl::stopControl` (por RPC: `[stpc]`).

> Hablándolo con Bartek, me comentaba la posibilidad de que el controlador se tenga que configurar atendiendo a las condiciones en las que realicemos el experimento, como puede ser el peso que exista sobre el cuello u otra serie de requisitos. ¿es esto así? ¿se podría afinar más el controlador para conseguir reducir esa sobreoscilación?

Propongo discutir esto en una nueva issue.
