### ISSUE TITLE
Pending tasks on the integration in Teo of the new controller

### ISSUE THREAD

**Issue by rsantos88** [HUMASoft/yarp-devices#7]
Pending tasks on the integration in Teo of the new controller for the soft-neck (editable):
1. - [x] Resolve issue: https://github.com/HUMASoft/yarp-devices/issues/8
2. - [x] Rename the "new-undocked" control for other name more representative 
3. - [x] Document: installation dependencies that the new library needs and the instructions to run the new-undocked control
4. - [x] Check that the new yarp-device of the imu publishes without errors
5. - [x] Update teo yarp-devices (commit  2fb7567908d9133d67158f8e3fdd254f2639d27b) to the current version and fix unwanted behaviors into the control (reaches first position and then stops moving)
6. - [ ] Merge  [soft-neck-integration](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/soft-neck-integration) branch to master branch in teo-configuration-files  
7. - [x] Pending to solve the decodePose conversion in pitch and roll ... [here](https://github.com/HUMASoft/yarp-devices/blob/sensor3DMGX510/libraries/YarpPlugins/SoftNeckControl/ICartesianControlImpl.cpp#L123-L125).

**Comment by rsantos88** [comment]
> 4. - [x] Check that the new yarp-device of the imu publishes without errors

Regarding this error, the IMU has been connected in the TEO manipulation computer (stuck to TEO's head)  and the waist has been moved, executing the following script that I have developed in python:
```python
# Author: Raul de Santos Rico
# Description: Script of a demo where Teo moves the trunk with the aim of stabilizing the neck
# CopyPolicy: released under the terms of the LGPLv2.1
# Python version: 2.7

from time import sleep
import threading
import csv
import yarp # imports YARP

robot = '/teo'
timeSpace = 12 # delays between trunk movements
DELAY = 0.01 # IMU sensor reading period
csvFile = "data.csv"

# YARP
yarp.Network.init()  # connect to YARP network

if yarp.Network.checkNetwork() != True:  # let's see if there was actually a reachable YARP network
    print('[error] Please try running yarp server')  # tell the user to start one with 'yarp server' if there isn't any
    quit()

#-- Trunk (TR)
optionsTR = yarp.Property()  # create an instance of Property, a nice YARP class for storing name-value (key-value) pairs
optionsTR.put('device','remote_controlboard')  # we add a name-value pair that indicates the YARP device
optionsTR.put('remote',robot+'/trunk')  # we add info on to whom we will connect
optionsTR.put('local','/demo'+robot+'/trunk')  # we add info on how we will call ourselves on the YARP network
ddTR = yarp.PolyDriver(optionsTR)  # create a YARP multi-use driver with the given options
posTR = ddTR.viewIPositionControl()  # make a position controller object we call 'pos'
encTR = ddTR.viewIEncoders() # encoders
axesTR = posTR.getAxes()  # retrieve number of joints

#create a new input port and open it
in_port = yarp.Port()
in_port.open("/softimu/in")
#connect up the output port to our input port
yarp.Network.connect("/teo/softimu/out", "/softimu/in")

# Configure acceleration
for joint in range(0, axesTR):
	posTR.setRefAcceleration(joint, 10) # manual por rpc --> set accs (20 20)

# Configure speed
sp = yarp.DVector(axesTR, 10)
posTR.setRefSpeeds(sp)

# writing CSV
start = yarp.now()
imu = yarp.Vector(2)

def writePossToCsv():
    with open(csvFile, 'w') as csvOutfile:
        csvwriter = csv.writer(csvOutfile, delimiter=',')
        csvwriter.writerow(['timestamp', 'axial-trunk', 'frontal-trunk', 'imu-roll', 'imu-pitch'])
        while(1):
            in_port.read(imu)
            print('timestam: ',round(yarp.now()-start,3))
            print('Trunk encoders: [', encTR.getEncoder(0),'], [',encTR.getEncoder(1),']')
            print('IMU: [', imu[0],', ',imu[1], ']')

            csvwriter.writerow([round(yarp.now()-start,3), encTR.getEncoder(0), encTR.getEncoder(1),
                imu[0], imu[1]])
            yarp.delay(DELAY)


writingThread = threading.Thread(target = writePossToCsv)
writingThread.start()

# move position
def moveTrunk(axial, frontal):
    tr = yarp.DVector(axesTR,0.0)
    tr = list([axial, frontal])
    posTR.positionMove(yarp.DVector(tr))
    while not posTR.checkMotionDone():
        sleep(0.1)

# Trunk movements
moveTrunk(20,-12)
yarp.delay(timeSpace)
moveTrunk(0,0)
yarp.delay(timeSpace)
moveTrunk(20,12)
yarp.delay(timeSpace)
moveTrunk(0,0)
yarp.delay(timeSpace)
moveTrunk(-20,-12)
yarp.delay(timeSpace)
moveTrunk(0,0)
yarp.delay(timeSpace)
moveTrunk(-20,12)
yarp.delay(timeSpace)
moveTrunk(0,0)
```

Graphing the results shows two garbage values ​:

![image](https://user-images.githubusercontent.com/15872457/109342202-cbbe1d00-786b-11eb-8b23-319ea927e420.png)

**Comment by rsantos88** [comment]
> 2. - [x] Rename the "new-undocked" control for other name more representative 

Regarding the name change, the new control systems will be renamed to:
`docked` -> `ioCoupled` (inclination orientation coupled control)
`undocked` -> `ioUncoupled` (inclination-orientation uncoupled control)
`newUndocked `-> `rpUncoupled` (roll-pitch uncoupled control)

Done at https://github.com/HUMASoft/yarp-devices/commit/2485677584db99ecc1837416f1d25518adaa9fb8

**Comment by rsantos88** [comment]
> 4. - [x] Check that the new yarp-device of the imu publishes without errors

solved removing `yarp.delay(DELAY)` when is reading. 

> 7. - [x] Pending to solve the decodePose conversion in pitch and roll ... [here](https://github.com/HUMASoft/yarp-devices/blob/sensor3DMGX510/libraries/YarpPlugins/SoftNeckControl/ICartesianControlImpl.cpp#L123-L125).

solved at https://github.com/roboticslab-uc3m/kinematics-dynamics/issues/192#issuecomment-862326252

**Comment by rsantos88** [comment]
> Update teo yarp-devices (commit 2fb7567908d9133d67158f8e3fdd254f2639d27b) to the current version and fix unwanted behaviors into the control (reaches first position and then stops moving)

Related to this issue, yarp-devices (master) has been updated to the latest version.

```bash
$ launchCanBus --from softNeck.ini
||| clearing context
||| adding context [launchCanBus]
||| configuring
||| default config file specified as softNeck.ini
||| checking [/home/humasoft/softNeck.ini] (pwd)
||| checking [/home/humasoft/.config/yarp/robots/default] (robot YARP_CONFIG_HOME)
||| checking [/home/humasoft/.local/share/yarp/robots/default] (robot YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/robots/default] (robot YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/robots/default] (robot YARP_CONFIG_DIRS)
||| checking [/usr/share/ubuntu/yarp/robots/default] (robot YARP_DATA_DIRS)
||| checking [/usr/local/share/yarp/robots/default] (robot YARP_DATA_DIRS)
||| checking [/usr/share/yarp/robots/default] (robot YARP_DATA_DIRS)
||| checking [/var/lib/snapd/desktop/yarp/robots/default] (robot YARP_DATA_DIRS)
||| checking [/usr/share/ubuntu/yarp/config/path.d] (robot path.d YARP_DATA_DIRS)
||| checking [/usr/local/share/yarp/config/path.d] (robot path.d YARP_DATA_DIRS)
||| found /usr/local/share/yarp/config/path.d
||| checking [/usr/local/share/humasoft-yarp-devices/robots/default] (robot yarp.d)
||| checking [/usr/local/share/roboticslab-kinematics-dynamics/robots/default] (robot yarp.d)
||| checking [/usr/local/share/roboticslab-yarp-devices/robots/default] (robot yarp.d)
||| checking [/usr/local/share/teo-configuration-files/robots/default] (robot yarp.d)
||| checking [/home/humasoft/.config/yarp/contexts/launchCanBus] (context YARP_CONFIG_HOME)
||| checking [/home/humasoft/.local/share/yarp/contexts/launchCanBus] (context YARP_DATA_HOME)
||| checking [/etc/xdg/xdg-ubuntu/yarp/contexts/launchCanBus] (context YARP_CONFIG_DIRS)
||| checking [/etc/xdg/yarp/contexts/launchCanBus] (context YARP_CONFIG_DIRS)
||| checking [/usr/share/ubuntu/yarp/contexts/launchCanBus] (context YARP_DATA_DIRS)
||| checking [/usr/local/share/yarp/contexts/launchCanBus] (context YARP_DATA_DIRS)
||| checking [/usr/share/yarp/contexts/launchCanBus] (context YARP_DATA_DIRS)
||| checking [/var/lib/snapd/desktop/yarp/contexts/launchCanBus] (context YARP_DATA_DIRS)
||| checking [/usr/local/share/humasoft-yarp-devices/contexts/launchCanBus] (context yarp.d)
||| found /usr/local/share/humasoft-yarp-devices/contexts/launchCanBus
||| checking [/usr/local/share/roboticslab-kinematics-dynamics/contexts/launchCanBus] (context yarp.d)
||| checking [/usr/local/share/roboticslab-yarp-devices/contexts/launchCanBus] (context yarp.d)
||| checking [/usr/local/share/teo-configuration-files/contexts/launchCanBus] (context yarp.d)
||| found /usr/local/share/teo-configuration-files/contexts/launchCanBus
||| checking [/usr/local/share/humasoft-yarp-devices/contexts/launchCanBus/softNeck.ini] (context)
||| found /usr/local/share/humasoft-yarp-devices/contexts/launchCanBus/softNeck.ini
[INFO]Checking for yarp network... 
||| finding file config.ini
||| checking [/home/humasoft/config.ini] (pwd)
||| found /home/humasoft/config.ini
[DEBUG]CanBusControlboard config: (buses (pcan-softNeck)) (description "CAN bus wrapper for TEO's soft neck") (device CanBusControlboard) (pcan-softNeck (id01-ipos id02-ipos id03-ipos)) (robotConfig {144 233 116 194 253 127 0 0}) 
[DEBUG]CanBusPeak config: (allowPermissive 0) (bitrate 1000000) (blockingMode 0) (description "PeakCAN bus on TEO's soft neck") (device CanBusPeak) (linInterpBufferSize 1) (linInterpMode pt) (linInterpPeriodMs 20) (port "/dev/pcan0") (robotConfig {144 233 116 194 253 127 0 0}) (rxBufferSize 500) (rxDelay 0.0) (threaded false) (txBufferSize 500) (txDelay 0.001) 
[INFO]Requested non-blocking mode for CAN device /dev/pcan0 
[INFO]Permissive mode flag for read/write operations on CAN device /dev/pcan0 set to false 
[INFO]Successfully opened CAN device /dev/pcan0 
[INFO]Acceptance filters cleared on CAN device /dev/pcan0 
[INFO]created device <CanBusPeak>. See C++ class roboticslab::CanBusPeak for documentation.
[WARNING]Illegal CAN bus buffer size or delay options 
[ERROR]Unable to configure broker of CAN bus device pcan-softNeck 
yarpdev: ***ERROR*** driver <CanBusControlboard> was found but could not open
[ERROR]CAN device neckBus configuration failure 
[INFO]RFModule failed to open.
```

**Comment by PeterBowman** [comment]
> ```shell
> [WARNING]Illegal CAN bus buffer size or delay options 
> ```

This is the reason, and it's complaining about an illegal configuration parameter ([source](https://github.com/roboticslab-uc3m/yarp-devices/blob/4a0b2b071e87735f169967d046f9c746357a31a8/libraries/YarpPlugins/CanBusControlboard/CanBusBroker.cpp#L51-L55)). More precisely, you need to set a non-zero value for `rxDelay` in:

https://github.com/HUMASoft/yarp-devices/blob/4cfc6b66da30c0de41b06e317da1bd81879550b7/share/robots/teoSoftNeck/config.ini#L8

I'd recommend the same value as `txDelay` (currently 1 ms). For reference, we're using 0.1 ms in TEO ([ref](https://github.com/roboticslab-uc3m/teo-configuration-files/blob/0e1304c093657c44f74d345ae617365b045f4d33/share/robots/teo/buses/pcan-leftArm.ini#L7-L10)).

**Comment by rsantos88** [comment]
> 5. - [x] Update teo yarp-devices (commit  2fb7567908d9133d67158f8e3fdd254f2639d27b) to the current version and fix unwanted behaviors into the control (reaches first position and then stops moving)

solved at https://github.com/HUMASoft/yarp-devices/commit/9f07e7b2013daa434bcc0776c15885222482e5af 
Thanks @PeterBowman

**Comment by PeterBowman** [comment]
>     6. * [ ]  Merge  [soft-neck-integration](https://github.com/roboticslab-uc3m/teo-configuration-files/tree/soft-neck-integration) branch to master branch in teo-configuration-files

Author here. This repo was designed to be self-contained and store its own config files. Pollution of the main TEO configuration environment is to be avoided, hence I'm going to delete said branch (which is a copy-paste of the files hosted here and will get obsolete soon, anyway) and mark this as closed/done.
