### ISSUE TITLE
Adapting yarp-devices to the new soft-arm 

### ISSUE THREAD

**Issue by rsantos88** [HUMASoft/yarp-devices#9]
In order to adapt `yarp-devices` configuration files to the soft arm, some data is required to complete the description of the parameters to be used in [teoSoftArm/config.ini](https://github.com/HUMASoft/yarp-devices/blob/soft-arm/share/robots/teoSoftArm/config.ini).
Looking at the data entered in the [CiA402SetupData](https://github.com/HUMASoft/CiA402Device_Archived/blob/8cd0f1d6ee64472657c2772a464c987d53a094a7/CiA402SetupData.cpp#L8) constructor used in [main.cpp](https://github.com/HUMASoft/Soft-Arm/blob/main/main/main.cpp#L17), I've included the configuration data of [this](https://github.com/HUMASoft/yarp-devices/blob/soft-arm/share/robots/teoSoftArm/config.ini#L77-L91) elements, but to be more correct it should indicate the final enum of each one (maxon-xxxxxxxx), and the data indicated in the description that appears for example in [config.ini](https://github.com/HUMASoft/yarp-devices/blob/soft-arm/share/robots/teoSoftNeck/config.ini#L77-L91) for the neck. I am not sure where to find this information.

**Comment by PeterBowman** [comment]
Probably solved by https://github.com/HUMASoft/yarp-devices/commit/842bbf81d6dc5b4fc2e97f98aa67f5a6f2a72bd4.
